package com.zoya.sudoku.data.db

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

/** Adds game_results (Stats feature) - region_layouts and puzzle_state are untouched, so the
 *  player's saved layouts and any in-progress puzzle survive the upgrade. */
val MIGRATION_2_3 = object : Migration(2, 3) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `game_results` (" +
                "`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, " +
                "`layoutId` INTEGER NOT NULL, " +
                "`difficulty` TEXT NOT NULL, " +
                "`correct` INTEGER NOT NULL, " +
                "`completedAt` INTEGER NOT NULL)"
        )
    }
}

/**
 * Reshapes puzzle_state from a single fixed-id=1 row (one in-progress game app-wide) into one row
 * per layoutId (one resumable game per раскладка), and adds pencil-mark storage (`notes`) plus
 * `updatedAt` for sorting the "Продолжить" list. The old app only ever had at most one row, so it
 * carries over as-is under its own layoutId - no data is lost.
 */
val MIGRATION_3_4 = object : Migration(3, 4) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `puzzle_state_new` (" +
                "`layoutId` INTEGER NOT NULL, " +
                "`solution` TEXT NOT NULL, " +
                "`givens` TEXT NOT NULL, " +
                "`board` TEXT NOT NULL, " +
                "`notes` TEXT NOT NULL, " +
                "`difficulty` TEXT NOT NULL, " +
                "`updatedAt` INTEGER NOT NULL, " +
                "PRIMARY KEY(`layoutId`))"
        )
        val emptyNotes = List(81) { "0" }.joinToString(",")
        db.execSQL(
            "INSERT INTO `puzzle_state_new` (layoutId, solution, givens, board, notes, difficulty, updatedAt) " +
                "SELECT layoutId, solution, givens, board, '$emptyNotes', difficulty, ${System.currentTimeMillis()} " +
                "FROM `puzzle_state`"
        )
        db.execSQL("DROP TABLE `puzzle_state`")
        db.execSQL("ALTER TABLE `puzzle_state_new` RENAME TO `puzzle_state`")
    }
}

/**
 * Drops the "one puzzle per layoutId" constraint: [PuzzleStateEntity.layoutId] stops being the
 * primary key, replaced by an autoincrement `id`. Before this, starting a fresh "Случайная игра"
 * that happened to land on a раскладка you already had in progress would silently overwrite that
 * progress (same PK = REPLACE). Now every started game gets its own row, so nothing is ever lost
 * to a collision - the "Продолжить" list tells same-layout entries apart by `updatedAt`. Existing
 * rows carry over as-is, each keeping its layoutId and gaining a fresh autogenerated id.
 */
val MIGRATION_4_5 = object : Migration(4, 5) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `puzzle_state_new` (" +
                "`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, " +
                "`layoutId` INTEGER NOT NULL, " +
                "`solution` TEXT NOT NULL, " +
                "`givens` TEXT NOT NULL, " +
                "`board` TEXT NOT NULL, " +
                "`notes` TEXT NOT NULL, " +
                "`difficulty` TEXT NOT NULL, " +
                "`updatedAt` INTEGER NOT NULL)"
        )
        db.execSQL(
            "INSERT INTO `puzzle_state_new` (layoutId, solution, givens, board, notes, difficulty, updatedAt) " +
                "SELECT layoutId, solution, givens, board, notes, difficulty, updatedAt FROM `puzzle_state`"
        )
        db.execSQL("DROP TABLE `puzzle_state`")
        db.execSQL("ALTER TABLE `puzzle_state_new` RENAME TO `puzzle_state`")
    }
}
